### ISSUE TITLE
Question for Chapter 1

### ISSUE THREAD

**Issue by Josh68** [vkarpov15/mastering-async-await#4]
Thank you so much for this book!

You say

```markdown
Both try/catch and catch() have their place. In particular, catch() makes it easier
to centralize your error handling. A common async/await novice mistake is 
putting try/catch at the top of every single function. If you want a common
handleError() function to ensure you're handing all errors, you're better off
using catch().
```
But you don't explain the reason why having an `async` function with a `try` including several lines of logic and a single `catch` block is worse than a similar `async` function with no `try/catch`, but called with a `.catch(errorHandler)`. Can you elaborate?

**Comment by vkarpov15** [comment]
Yeah sure! Two reasons:

1) `try/catch` won't catch promise rejections that occur if you return a promise. For example, the below code will result in an unhandled rejection, despite the try/catch:

```javascript
(async () => {
  try {
    return Promise.reject(new Error('Oops!'));
  } catch (err) {
    console.log('Caught', err.message);
  }
})();
```

This is an easy mistake to make, even for advanced users. At this point I recommend avoiding `return` in `try/catch` specifically because I've run into this issue a couple times.

2) `.catch()` is more composable. Given a hash of async functions, you can easily wrap them all with error handling:

```javascript
Object.keys(asyncFns).forEach(key => {
  const original = asyncFns[fn];
  asyncFns[fn] = function(params) {
    return original(params).catch(handleError);
  }
});
```

With `try/catch`, you need to put the same `try/catch` logic in every function, and that can lead to messy refactor if you ever want to change the `try/catch` logic you put in every function.

Does this make sense? Let me know if you have any more questions :+1:

**Comment by Josh68** [comment]
Thanks, Valeri, for the excellent explanation!

BTW, for the second example, I believe you meant

`Object.keys(asyncFns).forEach(fn => { ...`

Cheers,

Josh

**Comment by vkarpov15** [comment]
Thanks, I fixed that typo in my comment.

**Comment by Josh68** [comment]
> Thanks, I fixed that typo in my comment.

Thanks. I just pointed that out in case you were thinking of adding to the chapter. Async error handling patterns are something I'm still trying to nail down, so this context is really helpful.
